import { useState } from "react";
import { Link, useNavigate } from "react-router";
import { useAuth } from "../contexts/AuthContext";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await login(email,password);navigate("/")}catch(err){setError(err instanceof Error?err.message:"Unable to sign in");setBusy(false)}};
  return <div className="auth-body"><div className="animated-bg"><div className="animated-blob blob-1"/><div className="animated-blob blob-2"/><div className="animated-blob blob-3"/></div><div className="auth-container"><div className="auth-card"><div className="auth-avatar"><span className="material-symbols-rounded">login</span></div><h1 className="auth-title">Welcome Back</h1><p className="auth-subtitle">Sign in to Campus Core</p>{error&&<div className="banner" style={{color:"#ef4444"}}><span className="material-symbols-rounded">error</span>{error}</div>}<form onSubmit={submit}><div className="input-group"><span className="input-icon material-symbols-rounded">mail</span><input className="form-input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="input-group"><span className="input-icon material-symbols-rounded">lock</span><input className="form-input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="btn btn-primary btn-full" disabled={busy}>{busy?"Signing in…":"Sign In"}</button></form><div className="auth-footer">Don't have an account? <Link className="auth-link" to="/signup">Sign up</Link></div><div className="auth-footer"><Link className="auth-link" to="/reset-password" style={{color:"var(--text-muted)",fontWeight:400}}>Forgot password?</Link></div></div></div></div>;
}
