import { useState } from "react";
import { Link, useNavigate } from "react-router";
import { useAuth } from "../contexts/AuthContext";
import { searchUniversities } from "../lib/universities";

export default function Signup(){
 const {signup}=useAuth();const navigate=useNavigate();const [form,setForm]=useState({fullName:"",email:"",password:"",department:"",level:"100L",university:""});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);
 const set=(key:string,value:string)=>setForm({...form,[key]:value});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(!searchUniversities(form.university).some(u=>u.toLowerCase()===form.university.toLowerCase())){setError("Choose your university from the suggestions.");return}setBusy(true);try{await signup(form);window.alert("Account created. Please check your email to verify it.");navigate("/")}catch(err){setError(err instanceof Error?err.message:"Unable to create account");setBusy(false)}};
 return <div className="auth-body"><div className="animated-bg"><div className="animated-blob blob-1"/><div className="animated-blob blob-2"/><div className="animated-blob blob-3"/></div><div className="auth-container"><div className="auth-card"><div className="auth-avatar"><span className="material-symbols-rounded">person_add</span></div><h1 className="auth-title">Join the Hub</h1><p className="auth-subtitle">Start your digital journey at Campus Core</p>{error&&<div className="banner" style={{color:"#ef4444"}}><span className="material-symbols-rounded">error</span>{error}</div>}<form onSubmit={submit}><div className="input-group"><span className="input-icon material-symbols-rounded">badge</span><input className="form-input" placeholder="Full Name" value={form.fullName} onChange={e=>set("fullName",e.target.value)} required/></div><div className="input-group"><span className="input-icon material-symbols-rounded">mail</span><input className="form-input" type="email" placeholder="Email" value={form.email} onChange={e=>set("email",e.target.value)} required/></div><div className="input-group"><span className="input-icon material-symbols-rounded">lock</span><input className="form-input" type="password" placeholder="Password" value={form.password} onChange={e=>set("password",e.target.value)} minLength={6} required/></div><div className="input-group"><span className="input-icon material-symbols-rounded">category</span><input className="form-input" placeholder="Department" value={form.department} onChange={e=>set("department",e.target.value)} required/></div><div className="input-group"><span className="input-icon material-symbols-rounded">school</span><select className="form-input" value={form.level} onChange={e=>set("level",e.target.value)}><option>100L</option><option>200L</option><option>300L</option><option>400L</option><option>500L</option></select></div><div className="input-group university-search-container"><span className="input-icon material-symbols-rounded">home_work</span><input className="form-input" placeholder="Search your university" value={form.university} onFocus={()=>setShow(true)} onChange={e=>{set("university",e.target.value);setShow(true)}} required/>{show&&<div className="university-search-dropdown">{searchUniversities(form.university).slice(0,10).map(u=><div className="university-option" key={u} onClick={()=>{set("university",u);setShow(false)}}>{u}</div>)}</div>}</div><button className="btn btn-primary btn-full" disabled={busy}>{busy?"Creating account…":"Create Account"}</button></form><div className="auth-footer">Already have an account? <Link className="auth-link" to="/login">Sign In</Link></div></div></div></div>;
}
